# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ca79c79f860a0425d6bea7f1be4fcfa16a869066bc18809efa6e5bc0a01e5c792e5a1d2051ff986e6b843eae3354146a42f40545ecd02b5b1a6a7ea2d9dec95

test:
  secret_key_base: 49064fb57d330a97020c3b26a6c73d9d60919e12801019b28a6468c3863479c20162b81813e8b032a0e98f74df96d31edac1258b112d7e53f2afce0b7116876c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
